---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: ${PORT:${SERVER_PORT:0}} (this will cause a random, unused port to be assigned if none is specified)